### ISSUE TITLE
Segfault on array parsing

### ISSUE THREAD

**Issue by LaurentTreguier** [dlang-community/dsymbol#125]
There is a possible segfault here (this was added in b02f793f01c25568fc44e8371d07db955847046e):
https://github.com/dlang-community/dsymbol/blob/7eb7a3b5c57593b51d002ae4369501a1a395f31a/src/dsymbol/conversion/first.d#L1396-L1402
`al.argumentList` can be apparently null on some occasions; I don't know if it's supposed to be the case.

This can be reproduced with D-Scanner v0.7.0, when using `dscanner -S` on https://github.com/d-language-server/dls/blob/master/source/dls/tools/symbol_tool/internal/symbol_tool.d.
I'm trying to figure out which part of the file exactly triggers it.
Here is a backtrace, if it's of any use:
[bt.txt](https://github.com/dlang-community/dsymbol/files/2872291/bt.txt)

Tested on Linux x64 with dmd 2.084.1

**Comment by LaurentTreguier** [comment]
Ok, it happens with this for example:
```d
auto a = true ? [42] : [];
```
But not with this:
```d
auto a = true ? [42] : [42];
```
Or this:
```d
int[] a = true ? [42] : [];
```
It seems to have a problem with empty array literals and auto variable declarations.

**Comment by Basile-z** [comment]
Thanks for this good report. Yet another case where the safe access operator would have saved us.

**Comment by Basile-z** [comment]
More likely a dparse problem actually.
