### ISSUE TITLE
Code completion for modules with public imports

### ISSUE THREAD

**Issue by RUSshy** [dlang-community/dsymbol#156]
Hello

Right now if i import module, let's say: ``std.string`` and wants to use ``startsWith`` function, it won't show up  in code completion with dcd/dls

The module ``std.string``  have public import ``public import std.algorithm.searching : startsWith, endsWith, count; ``

When building the ModuleCache, it should check also for public import from that module

**Comment by WebFreak001** [comment]
not fixed

**Comment by RUSshy** [comment]
msg to @p0nce aka Guillaume Piolat

I suspect that is you that is trying to silent me on discord by banning me

I will now stop all my contributions

You guys don't deserve my free time, fuck you whoever banned me

You lucky i don't know you IRL, you deserve some good slap in your face

I don't allow anybody to re-open this PR

LICENCE of all my PRs = PROPRIETARY
