### ISSUE TITLE
Assertion failure in `dsymbol.modulecache`

### ISSUE THREAD

**Issue by chances** [dlang-community/dsymbol#157]
See this CI run: https://github.com/chances/teraflop-d/pull/11/checks?check_run_id=1817643809#step:8:41

I'm not sure if this is a problem with d-scanner directly, see https://github.com/dlang-community/D-Scanner/issues/827

```
core.exception.AssertError@../../../.dub/packages/dsymbol-0.11.3/dsymbol/src/dsymbol/modulecache.d(261): Assertion failure
```

https://github.com/dlang-community/dsymbol/blob/b8920c2a4593e24d1ced91f8f0bce9e50f598e4d/src/dsymbol/modulecache.d#L261

**Comment by WebFreak001** [comment]
this might be fixed now with DSymbol being integrated into DCD. If you still run into this issue, please open another issue in DCD.
