### ISSUE TITLE
(w,d)string, size_t, and ptrdiff_t are missing

### ISSUE THREAD

**Issue by SSoulaimane** [dlang-community/dsymbol#43]
`DSymbol.type` for string types, size_t, and ptrdiff_t is null.

**Comment by Hackerpilot** [comment]
What exactly do you mean? They're aliases in object.d and not real built-in types.

**Comment by SSoulaimane** [comment]
correct, I've been missing some sleep lately, and just last i read  the definition of size_t in object.d. sorry closing.
