### ISSUE TITLE
It will break soon due to `theAllocator` type change

### ISSUE THREAD

**Issue by BBasile** [dlang-community/dsymbol#62]
It was a IAllocator, it will be an RCIAllocator. The breakage will propagate to DCD and D-Scanner. You can have a preview of the future problem here: https://travis-ci.org/dlang-community/dsymbol/jobs/339183618#L586.

**Comment by wilzbach** [comment]
How about using [`stdx-allocator`](https://github.com/dlang-community/stdx-allocator)?

See also: https://forum.dlang.org/post/730a99d2-1043-19b7-551a-c6f57790f422@erdani.org

**Comment by BBasile** [comment]
Yeah that's option number 1. Number 2 is to adapt the code and use some `static if` / `version`

**Comment by BBasile** [comment]
The problem is that there's a bunch of bug fixes that cant be merged because of this.

**Comment by BBasile** [comment]
\+ git submodule \+ update JSON

**Comment by wilzbach** [comment]
https://github.com/dlang-community/dsymbol/pull/63

> + git submodule + update JSON

Yeah, but we would need to do the same for `static if` and at least with the DUB package, we hopefully don't need to do this again.

**Comment by BBasile** [comment]
okay, let's use our fork then

**Comment by BBasile** [comment]
i close but there are the DCD / D-Scanner PR to do too

**Comment by wilzbach** [comment]
I know :/

See also: https://github.com/dlang-community/discussions/issues/33

**Comment by BBasile** [comment]
Before i'll manage the stalled PR from @SSoulaimane.
