### ISSUE TITLE
Segfault when trying to complete `import std.getopt : `

### ISSUE THREAD

**Issue by LaurentTreguier** [dlang-community/dsymbol#76]
When trying to complete the line `import std.getopt : ` with DCD, I am getting a segfault. I'm not sure whether the problem really comes from dsymbol, but this is at least where the segfault originates from (https://github.com/dlang-community/dsymbol/blob/v0.3.7/src/dsymbol/symbol.d#L258)
Versions of everything I'm using:
- DCD 0.9.7
- dsymbol 0.3.7
- libdparse 0.8.5
- DMD 2.080.0
Here is the demangled backtrace I get from GDB, if it's of any use:
[backtrace.txt](https://github.com/dlang-community/dsymbol/files/2019292/backtrace.txt)

**Comment by BBasile** [comment]
completion is not supposed to work at this point (colon following import) but line 258 is

```d
if (qualifier == SymbolQualifier.selectiveImport && type !is null
```

so unsafe access to the `qualifier` member when it is null apparently.

**Comment by LaurentTreguier** [comment]
What do you mean, completion is not supposed to work ? Up until now, I had completion showing symbols in a module after a colon following an import statement

**Comment by BBasile** [comment]
Damn, sorry. you're right. I didn't notice this until just now, which is kind of funny since i use DCD much ;)

**Comment by BBasile** [comment]
so your report makes more sense now... it happens never but with std.getopt.

**Comment by LaurentTreguier** [comment]
Retrying a bit, it seems it doesn't even always happen. It happens right after DCD starts, but after doing other things in another file and trying again, it worked fine :/

**Comment by BBasile** [comment]
maybe the dirEntries bug.

**Comment by BBasile** [comment]
I manage to get the same crash on each try with `import dparse.lexer : is|`

**Comment by BBasile** [comment]
Actually DCD crashes on any attempt to get completion on a partial selective import identifier.

**Comment by BBasile** [comment]
The segfault is when reading type. It's not null but has a value of 0x50 for some reason...
