### ISSUE TITLE
Segfault on garbage collection

### ISSUE THREAD

**Issue by LaurentTreguier** [dlang-community/dsymbol#81]
The continuation of https://github.com/dlang-community/containers/issues/111

**Comment by LaurentTreguier** [comment]
So I found a workaround for this. I was instantiating a `ModuleCache` with `new`, which lead to it being managed by the GC. Instantiating it on the stack like a normal struct, the problem goes away.
I don't know if this issue should be closed or not; I don't have this weird problem anymore, but technically the problem could still happen with using `new`.

**Comment by WebFreak001** [comment]
we are using GCAllocator now in DCD, so this issue should be gone now
